### ISSUE TITLE
RangeError [Error]: WebAssembly.instantiate(): Out of memory: wasm memory

### ISSUE THREAD

**Issue by brendan1212** [jasnell/piscina#158] opened 2021-11-13 04:27 UTC
Running into this error when running in production.
![Screen Shot 2021-11-12 at 9 18 33 PM](https://user-images.githubusercontent.com/46540659/141605388-58b89777-d5a2-4997-9c32-6a7c57b4ad92.png)

I have a use case where I'm running a non-api nodejs instance for crunching large amounts of data. In Google Cloud Compute I have a system set up with 128vCPUs and 512GB memory, although I am unsure how to set `resourceLimits` (or other options for that matter) in Piscina to run this correctly.

The only other option I'm currently implementing is `--max-old-space-size=2048`(could double this), assuming that what I've read is correct and this is per-worker-thread...

Any advice?

EDIT: Should mention that I’m running into this range error upon instantiating the initial Piscina workers, not later during the actual processing.

**Comment by sahilguptasc** [comment] 2021-11-15 07:08
I am facing the same error. My app is able to serve ~100K requests before running out of memory.
```
node:internal/event_target:777
  process.nextTick(() => { throw err; });
                           ^
RangeError [Error]: WebAssembly.instantiate(): Out of memory: wasm memory
    at node:internal/deps/cjs-module-lexer/dist/lexer:1:33593
    at async initCJSParse (node:internal/modules/esm/translators:69:5)
    at async ESMLoader.commonjsStrategy (node:internal/modules/esm/translators:176:18)
    at async link (node:internal/modules/esm/module_job:70:21)
Emitted 'error' event on Piscina instance at:
    at EventEmitterReferencingAsyncResource.runInAsyncScope (node:async_hooks:199:9)
    at Piscina.emit (/home/sahilgupta/WebstormProjects/node-packages/db-driver-v2-client/node_modules/eventemitter-asyncresource/dist/src/index.js:30:35)
    at Worker.<anonymous> (/home/sahilgupta/WebstormProjects/node-packages/db-driver-v2-client/node_modules/piscina/dist/src/index.js:473:38)
    at Worker.emit (node:events:390:28)
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:562:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
    
Node.js v17.1.0
```
Though I am not able to locate the exact reason why it is going out of memory, but my hunch is that there is a memory leak somewhere in your application. My best guess is it occurs when the results from Worker threads is returned.  The return value is cloned rather than transferred. See: https://github.com/piscinajs/piscina#static-method-movevalue. Assuming this is the case, you'd need to use the move() function when returning the result from your function. In my application, worker threads are calling a function defined in C++ using NAPI. So I'm unable to use the move() function since it is only available in Javascript and not in C++. I had 3 questions:
1. How to verify that this is error is caused by memory leak?
2. If yes, how to identify where the leak is occurring?
3. If the leak is occurring when the return value is cloned, how can I use the move() method in a NAPI C++ function?

PS: @jasnell - You mentioned here (https://www.nearform.com/blog/learning-to-swim-with-piscina-the-node-js-worker-pool/ ) about a memory leak. What was the root cause for that?

Update: I created another function in Node that called the function in Napi layer. I then used move() function when returning the result from the Node function. But it is still going out of memory.

**Comment by brendan1212** [comment] 2021-11-15 20:03
@sahilguptasc I can confirm that it isn't a memory leak in my case since the error is thrown shortly after my application starts. I'm getting `process.memoryUsage().rss` at well under 300MB. `--max-old-space-size=4096`

In my case, I'm trying to queue 5400 iterations in the pool. Have tried to throttle this loop pretty heavily at 250ms but still getting the error.

EDIT: Also I haven't yet returned any values from any worker.

**Comment by brendan1212** [comment] 2021-11-16 02:19
Also forgot to mention that I'm now writing & reading these 5400 parameter payloads to file via stream, so all that data isn't hanging out in memory. Error persists.

**Comment by terminal69** [comment] 2021-12-13 06:41
Just browsing and came across this.
Had a similar problem using WASM in my own implementation of worker threads a few months ago (not using piscina)
It was also on loading the worker thread - "RangeError: WebAssembly.Instance(): Out of memory: wasm memory"
Possibly related to https://github.com/nodejs/node/issues/30017
If you can, check virtual memory usage

**Comment by brendan1212** [comment] 2021-12-22 02:22
> Just browsing and came across this. Had a similar problem using WASM in my own implementation of worker threads a few months ago (not using piscina) It was also on loading the worker thread - "RangeError: WebAssembly.Instance(): Out of memory: wasm memory" Possibly related to [nodejs/node#30017](https://github.com/nodejs/node/issues/30017) If you can, check virtual memory usage

Hi @terminal69. Thanks a bunch -- this looks like the right direction but I'm having trouble finding a concrete fix in those threads. Could you elaborate on the steps you took to fix your error?

**Comment by terminal69** [comment] 2021-12-24 12:53
> Hi @terminal69. Thanks a bunch -- this looks like the right direction but I'm having trouble finding a concrete fix in those threads. Could you elaborate on the steps you took to fix your error?

@pachiraDIG sorry, forgot to mention that we stopped using WASM in our project temporarily
Working on a test case now to recreate the problem.
How do you create your WASM module? I am using rust wasm-pack. It seems that it is allocating 10GB of virtual memory per worker, so I reach a limit of 100 workers before getting the `Out of memory: wasm memory` error

**Comment by terminal69** [comment] 2021-12-26 06:34
@pachiraDIG in my test case at https://github.com/terminal69/wasm-worker-memory-test - upgrading to nodejs 17.2 seems to solve the problem however I do not know if high virtual memory usage would still be an issue for you on Google Cloud Compute.

**Comment by tniessen** [comment] 2021-12-26 11:46
> there is a memory leak somewhere in your application

Note that the error happens in `instantiate`, which means that, assuming the WebAssembly module specifies a proper initial memory size, the error is likely not caused by dynamic memory growth. Instead, it could be caused by a failure in `BackingStore::AllocateWasmMemory`, which can be due to a number of reasons and limitations. For example, you could try increasing `--wasm-max-mem-pages` to allow more memory per WebAssembly instance.

**Comment by brendan1212** [comment] 2021-12-28 03:54
@terminal69 Upgrading nodejs to latest (17.3.0) fixed it for me as well.
😁 See that? That's a happy face.
Thanks.

**Comment by asheroto** [comment] 2022-02-21 00:28
Using node 17.4.0 and having this issue.

**Comment by hwakstar** [comment] 2023-03-30 18:04
[nodemon] starting `node server.js`
/home/server/node_modules/tiny-secp256k1/lib/cjs/wasm_loader.cjs:13
const instance = new WebAssembly.Instance(mod, imports);
                 ^

RangeError: WebAssembly.Instance(): Out of memory: wasm memory
    at Object.<anonymous> (/home/aserver/node_modules/tiny-secp256k1/lib/cjs/wasm_loader.cjs:13:18)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/pandapaygo/aserver/node_modules/tiny-secp256k1/lib/cjs/index.cjs:6:26)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1245:10)
    at Module.load (node:internal/modules/cjs/loader:1069:32)
    at Function.Module._load (node:internal/modules/cjs/loader:904:12)
    at Module.require (node:internal/modules/cjs/loader:1093:19)
    at require (node:internal/modules/cjs/helpers:108:18)
    at Object.<anonymous> (/home/server/controller/crypto.controller.js:6:13)
    at Module._compile (node:internal/modules/cjs/loader:1191:14)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by metcoder95** [comment] 2023-06-12 21:28
@brendan1212 can you confirm if this is stils valid?

**Comment by brendan1212** [comment] 2023-06-12 21:36
> 

I ended up switching to using the node cluster module.

**Comment by metcoder95** [comment] 2023-06-12 21:42
Sounds fair, closing issue for now. I think it might be worth it to explore in the future, thanks for the context though 🙂

**Closed as completed by metcoder95** 2023-06-12 21:42 UTC
