### ISSUE TITLE
TypeScript: Could not find a declaration file for module 'piscina'

### ISSUE THREAD

**Issue by brettwillis** [jasnell/piscina#362] opened 2023-06-18 22:37 UTC
With TypeScript (v5.1.3), using `"moduleResolution": "NodeNext"`, Pinsina cannot be imported:

```TypeScript
import { Piscina } from 'piscina';
//                      ~~~~~~~~~
// Could not find a declaration file for module 'piscina'. '...node_modules/piscina/dist/esm-wrapper.mjs' implicitly has an 'any' type.
// There are types at '...node_modules/piscina/dist/src/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'piscina' library may need to update its package.json or typings.ts(7016)
```

**Comment by metcoder95** [comment] 2023-06-19 20:28
Hi @brettwillis, thanks for reporting.

Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the issue with similar conditions as yours?

**Comment by Giftia** [comment] 2023-06-20 06:25
try this, no curly brace
```ts
import Piscina from 'piscina';
```

**Comment by brettwillis** [comment] 2023-06-20 07:33
Yeah I tried all sorts there, but nothing is going to work while TypeScript cannot find the types for the module itself.

> Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce the issue with similar conditions as yours?

Yep I'll do that.

**Comment by brettwillis** [comment] 2023-06-20 07:42
@metcoder95 see attached [piscina.zip](https://github.com/piscinajs/piscina/files/11797360/piscina.zip).

**Comment by metcoder95** [comment] 2023-06-27 19:33
Sorry, I haven't had the time yet to visit this. I'm planning to go through it this week 👍

**Comment by brettwillis** [comment] 2023-06-27 20:38
No worries, I'm guessing it's a pretty easy fix, but haven't had the time to look at it myself either.

**Comment by Janpot** [comment] 2023-06-28 14:58
I had this happening for me as well when changing `moduleResolution` from `node` to `bundler`

**Comment by hugebdu** [comment] 2023-07-02 10:04
looks like adding types again under `exports` section in `package.json` solves the issue:


```diff
  "name": "piscina",
  "version": "4.0.0",
  "description": "A fast, efficient Node.js Worker Thread Pool implementation",
  "main": "./dist/src/index.js",
  "exports": {
    "import": "./dist/esm-wrapper.mjs",
    "require": "./dist/src/index.js",
+   "types": "./dist/src/index.d.ts"
  },
  "types": "./dist/src/index.d.ts",
```

**Comment by metcoder95** [comment] 2023-07-02 20:37
Nice finding. Haven't tried yet to reproduce it, but it seems like a good course of action. Would you like to open a PR for it?

**Comment by hugebdu** [comment] 2023-07-03 07:04
Apparently the [source code](https://github.com/piscinajs/piscina/blob/current/package.json#L7) for `package.json` contains that entry, however in published version it is absent:

```
wget -qO- https://registry.npmjs.org/piscina/-/piscina-4.0.0.tgz | tar xvzO package/package.json | cat
```

**Comment by metcoder95** [comment] 2023-09-15 08:01
@hugebdu can you verify this stills the case with the newest version?
cc: @brettwillis

**Comment by brettwillis** [comment] 2023-09-17 21:55
@metcoder95 confirmed that `v4.1.0` fixed the issue described in the original post. Thanks.

It's worth noting that TypeScript only allows default-import of this module. 

```ts
import { Piscina } from 'piscina';
//                      ~~~~~~~~~
// This module can only be referenced with ECMAScript imports/exports by turning on the 'allowSyntheticDefaultImports' flag and referencing its default export.ts(2497)
```

However with `allowSyntheticDefaultImports: true`, then the following works perfectly fine:

```ts
import piscina from 'piscina';

const pool = new piscina.Piscina({
  ...
});
```

Which is fine I guess, just thought I'd mention it.

**Comment by metcoder95** [comment] 2023-09-18 07:56
Got it, thanks! Those are partially good news 😅 
I'll check out the import issue, but I'll close the issue as completed for now. Thanks!

**Closed as completed by metcoder95** 2023-09-18 07:56 UTC
Labels: typescript
